-- Blackbook's schema, as one baseline.
--
-- Squashed from the six migrations the schema was built up through during
-- development. Two of those were corrections and are absorbed rather than
-- replayed: the audit trail's foreign keys are declared SET NULL in the
-- generated DDL below, and the append-only trigger appears once, in its final
-- form.
--
-- The live database has already run all six. The migrator decides what to
-- apply by comparing this journal entry's `when` against the newest row in
-- `drizzle.__drizzle_migrations`, never by hash, so the entry keeps the last of
-- those six timestamps: an existing database skips this file, and an empty one
-- builds the whole schema from it. The superseded rows are left in that
-- bookkeeping table, since only the newest is ever read.
--
-- Everything down to the search indexes is generated by drizzle-kit from
-- `src/db/schema`. Everything after is hand-written, because trigram indexes on
-- generated columns, PL/pgSQL functions, triggers and row-level security are
-- outside what a schema definition can express. Regenerating the first half
-- means re-appending the second.

CREATE TYPE "public"."activity_action" AS ENUM('created', 'updated', 'archived', 'restored', 'linked', 'unlinked', 'interaction_logged', 'preference_updated');--> statement-breakpoint
CREATE TYPE "public"."activity_entity" AS ENUM('customer', 'household', 'milestone', 'interaction', 'task', 'preference');--> statement-breakpoint
CREATE TYPE "public"."booking_lead_time" AS ENUM('last_minute', 'under_1_month', 'one_to_three_months', 'three_to_six_months', 'six_months_plus');--> statement-breakpoint
CREATE TYPE "public"."budget_range" AS ENUM('upto_5l', '5l_10l', '10l_25l', '25l_50l', '50l_plus', 'no_ceiling');--> statement-breakpoint
CREATE TYPE "public"."cabin_class" AS ENUM('economy', 'premium_economy', 'business', 'first', 'private');--> statement-breakpoint
CREATE TYPE "public"."client_status" AS ENUM('active', 'inactive');--> statement-breakpoint
CREATE TYPE "public"."dietary_preference" AS ENUM('no_restriction', 'vegetarian', 'vegan', 'jain', 'halal', 'kosher', 'pescatarian', 'gluten_free', 'other');--> statement-breakpoint
CREATE TYPE "public"."direct_flight_preference" AS ENUM('always_direct', 'prefer_direct', 'no_preference');--> statement-breakpoint
CREATE TYPE "public"."directive_kind" AS ENUM('do', 'dont');--> statement-breakpoint
CREATE TYPE "public"."experience_style" AS ENUM('private_bespoke', 'small_group', 'exclusive_access', 'off_the_beaten_path', 'classic_highlights', 'relaxed_unstructured');--> statement-breakpoint
CREATE TYPE "public"."fine_dining_preference" AS ENUM('essential', 'enjoys', 'occasional', 'prefers_casual');--> statement-breakpoint
CREATE TYPE "public"."gender" AS ENUM('male', 'female', 'other', 'prefer_not_to_say');--> statement-breakpoint
CREATE TYPE "public"."household_role" AS ENUM('primary', 'spouse', 'partner', 'child', 'parent', 'sibling', 'other');--> statement-breakpoint
CREATE TYPE "public"."household_travel_pattern" AS ENUM('couple', 'family', 'multi_generational');--> statement-breakpoint
CREATE TYPE "public"."interaction_type" AS ENUM('call', 'whatsapp', 'email', 'meeting', 'trip', 'note', 'other');--> statement-breakpoint
CREATE TYPE "public"."milestone_status" AS ENUM('active', 'archived');--> statement-breakpoint
CREATE TYPE "public"."milestone_type" AS ENUM('birthday', 'wedding_anniversary', 'work_anniversary', 'religious', 'memorial', 'other');--> statement-breakpoint
CREATE TYPE "public"."preference_kind" AS ENUM('destination', 'travel_style', 'travel_season', 'hotel_brand', 'hotel_property', 'room_type', 'bed_preference', 'view_preference', 'airline', 'loyalty_programme', 'seat_preference', 'flight_timing', 'cuisine', 'restaurant', 'allergy', 'beverage_preference', 'interest', 'activity', 'luxury_brand');--> statement-breakpoint
CREATE TYPE "public"."preference_polarity" AS ENUM('prefer', 'wishlist', 'avoid');--> statement-breakpoint
CREATE TYPE "public"."task_priority" AS ENUM('low', 'normal', 'high');--> statement-breakpoint
CREATE TYPE "public"."task_status" AS ENUM('open', 'in_progress', 'done', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."travel_frequency" AS ENUM('less_than_once_a_year', 'one_to_two_per_year', 'three_to_four_per_year', 'five_plus_per_year');--> statement-breakpoint
CREATE TYPE "public"."travelling_party" AS ENUM('solo', 'couple', 'family_young_children', 'family_teens', 'multi_generational', 'friends', 'business');--> statement-breakpoint
CREATE TYPE "public"."user_role" AS ENUM('admin', 'manager', 'rm', 'viewer');--> statement-breakpoint
CREATE SEQUENCE "public"."customer_ref_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100 CACHE 1;--> statement-breakpoint
CREATE SEQUENCE "public"."household_ref_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 100 CACHE 1;--> statement-breakpoint
CREATE TABLE "app_account" (
	"id" text PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"account_id" text NOT NULL,
	"provider_id" text NOT NULL,
	"access_token" text,
	"refresh_token" text,
	"access_token_expires_at" timestamp with time zone,
	"refresh_token_expires_at" timestamp with time zone,
	"scope" text,
	"id_token" text,
	"password" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "app_session" (
	"id" text PRIMARY KEY NOT NULL,
	"token" text NOT NULL,
	"user_id" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"ip_address" text,
	"user_agent" text,
	"impersonated_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "app_session_token_unique" UNIQUE("token")
);
--> statement-breakpoint
CREATE TABLE "app_user" (
	"id" text PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"email" text NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"image" text,
	"role" "user_role" DEFAULT 'viewer' NOT NULL,
	"banned" boolean DEFAULT false,
	"ban_reason" text,
	"ban_expires" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "app_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "app_verification" (
	"id" text PRIMARY KEY NOT NULL,
	"identifier" text NOT NULL,
	"value" text NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "client_directive" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" uuid NOT NULL,
	"kind" "directive_kind" NOT NULL,
	"body" text NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "customer" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ref" text DEFAULT 'CUST-' || lpad(nextval('customer_ref_seq')::text, 5, '0') NOT NULL,
	"household_id" uuid,
	"household_role" "household_role",
	"first_name" text NOT NULL,
	"last_name" text,
	"preferred_name" text,
	"mobile" text,
	"mobile_normalized" text GENERATED ALWAYS AS (nullif(regexp_replace(coalesce(mobile, ''), '[^0-9]', '', 'g'), '')) STORED,
	"whatsapp" text,
	"whatsapp_normalized" text GENERATED ALWAYS AS (nullif(regexp_replace(coalesce(whatsapp, ''), '[^0-9]', '', 'g'), '')) STORED,
	"email" text,
	"date_of_birth" date,
	"gender" "gender",
	"nationality" text,
	"city" text,
	"address" text,
	"location_url" text,
	"location_lat" text,
	"location_lng" text,
	"primary_rm_id" text,
	"customer_since" date DEFAULT now() NOT NULL,
	"status" "client_status" DEFAULT 'active' NOT NULL,
	"client_dna" text,
	"last_interaction_at" timestamp with time zone,
	"profile_updated_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" text,
	"updated_by" text,
	"archived_at" timestamp with time zone,
	CONSTRAINT "customer_ref_unique" UNIQUE("ref")
);
--> statement-breakpoint
CREATE TABLE "household" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"ref" text DEFAULT 'HH-' || lpad(nextval('household_ref_seq')::text, 5, '0') NOT NULL,
	"name" text NOT NULL,
	"city" text,
	"primary_customer_id" uuid,
	"travel_pattern" "household_travel_pattern",
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" text,
	"updated_by" text,
	"archived_at" timestamp with time zone,
	CONSTRAINT "household_ref_unique" UNIQUE("ref")
);
--> statement-breakpoint
CREATE TABLE "customer_preference_profile" (
	"customer_id" uuid PRIMARY KEY NOT NULL,
	"travel_typical_trip_nights" integer,
	"travel_party" "travelling_party",
	"travel_frequency" "travel_frequency",
	"travel_budget_range" "budget_range",
	"travel_booking_lead_time" "booking_lead_time",
	"travel_notes" text,
	"hotel_notes" text,
	"flight_cabin" "cabin_class",
	"flight_direct_preference" "direct_flight_preference",
	"flight_notes" text,
	"dining_dietary" "dietary_preference",
	"dining_fine_dining" "fine_dining_preference",
	"dining_notes" text,
	"lifestyle_experience_style" "experience_style",
	"lifestyle_notes" text,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" text
);
--> statement-breakpoint
CREATE TABLE "customer_preference" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" uuid NOT NULL,
	"option_id" uuid NOT NULL,
	"polarity" "preference_polarity" DEFAULT 'prefer' NOT NULL,
	"note" text,
	"rank" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" text
);
--> statement-breakpoint
CREATE TABLE "preference_option" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" "preference_kind" NOT NULL,
	"slug" text NOT NULL,
	"label" text NOT NULL,
	"grouping" text,
	"is_custom" boolean DEFAULT false NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" text
);
--> statement-breakpoint
CREATE TABLE "activity_log" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"entity_type" "activity_entity" NOT NULL,
	"entity_id" uuid NOT NULL,
	"action" "activity_action" NOT NULL,
	"customer_id" uuid,
	"household_id" uuid,
	"summary" text NOT NULL,
	"changes" jsonb,
	"actor_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "interaction" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" uuid,
	"household_id" uuid,
	"type" "interaction_type" NOT NULL,
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"summary" text NOT NULL,
	"details" text,
	"logged_by" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "interaction_owner_check" CHECK (customer_id is not null or household_id is not null)
);
--> statement-breakpoint
CREATE TABLE "milestone" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" uuid,
	"household_id" uuid,
	"type" "milestone_type" NOT NULL,
	"title" text NOT NULL,
	"date" date NOT NULL,
	"recurs_annually" boolean DEFAULT true NOT NULL,
	"month_of_year" smallint GENERATED ALWAYS AS (extract(month from date)::smallint) STORED,
	"day_of_month" smallint GENERATED ALWAYS AS (extract(day from date)::smallint) STORED,
	"celebration_style" text,
	"notes" text,
	"reminder_days_before" integer[] DEFAULT '{30,7,1}' NOT NULL,
	"status" "milestone_status" DEFAULT 'active' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" text,
	CONSTRAINT "milestone_owner_check" CHECK ((customer_id is not null) <> (household_id is not null))
);
--> statement-breakpoint
CREATE TABLE "task" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"title" text NOT NULL,
	"details" text,
	"customer_id" uuid,
	"household_id" uuid,
	"assignee_id" text,
	"due_date" date,
	"status" "task_status" DEFAULT 'open' NOT NULL,
	"priority" "task_priority" DEFAULT 'normal' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" text,
	"completed_at" timestamp with time zone
);
--> statement-breakpoint
ALTER TABLE "app_account" ADD CONSTRAINT "app_account_user_id_app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "app_session" ADD CONSTRAINT "app_session_user_id_app_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."app_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_directive" ADD CONSTRAINT "client_directive_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer" ADD CONSTRAINT "customer_household_id_household_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."household"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer" ADD CONSTRAINT "customer_primary_rm_id_app_user_id_fk" FOREIGN KEY ("primary_rm_id") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer" ADD CONSTRAINT "customer_created_by_app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer" ADD CONSTRAINT "customer_updated_by_app_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "household" ADD CONSTRAINT "household_primary_customer_id_customer_id_fk" FOREIGN KEY ("primary_customer_id") REFERENCES "public"."customer"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "household" ADD CONSTRAINT "household_created_by_app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "household" ADD CONSTRAINT "household_updated_by_app_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_preference_profile" ADD CONSTRAINT "customer_preference_profile_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_preference_profile" ADD CONSTRAINT "customer_preference_profile_updated_by_app_user_id_fk" FOREIGN KEY ("updated_by") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_preference" ADD CONSTRAINT "customer_preference_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_preference" ADD CONSTRAINT "customer_preference_option_id_preference_option_id_fk" FOREIGN KEY ("option_id") REFERENCES "public"."preference_option"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "customer_preference" ADD CONSTRAINT "customer_preference_created_by_app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "preference_option" ADD CONSTRAINT "preference_option_created_by_app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_log" ADD CONSTRAINT "activity_log_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_log" ADD CONSTRAINT "activity_log_household_id_household_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."household"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "activity_log" ADD CONSTRAINT "activity_log_actor_id_app_user_id_fk" FOREIGN KEY ("actor_id") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction" ADD CONSTRAINT "interaction_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction" ADD CONSTRAINT "interaction_household_id_household_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."household"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "interaction" ADD CONSTRAINT "interaction_logged_by_app_user_id_fk" FOREIGN KEY ("logged_by") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "milestone" ADD CONSTRAINT "milestone_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "milestone" ADD CONSTRAINT "milestone_household_id_household_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."household"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "milestone" ADD CONSTRAINT "milestone_created_by_app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_customer_id_customer_id_fk" FOREIGN KEY ("customer_id") REFERENCES "public"."customer"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_household_id_household_id_fk" FOREIGN KEY ("household_id") REFERENCES "public"."household"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_assignee_id_app_user_id_fk" FOREIGN KEY ("assignee_id") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "task" ADD CONSTRAINT "task_created_by_app_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."app_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "app_account_user_idx" ON "app_account" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_session_user_idx" ON "app_session" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "app_user_role_idx" ON "app_user" USING btree ("role");--> statement-breakpoint
CREATE INDEX "app_verification_identifier_idx" ON "app_verification" USING btree ("identifier");--> statement-breakpoint
CREATE INDEX "client_directive_customer_idx" ON "client_directive" USING btree ("customer_id","kind");--> statement-breakpoint
CREATE INDEX "customer_household_idx" ON "customer" USING btree ("household_id");--> statement-breakpoint
CREATE INDEX "customer_rm_idx" ON "customer" USING btree ("primary_rm_id");--> statement-breakpoint
CREATE INDEX "customer_status_idx" ON "customer" USING btree ("status");--> statement-breakpoint
CREATE INDEX "customer_archived_idx" ON "customer" USING btree ("archived_at");--> statement-breakpoint
CREATE INDEX "customer_last_interaction_idx" ON "customer" USING btree ("last_interaction_at");--> statement-breakpoint
CREATE INDEX "customer_mobile_normalized_idx" ON "customer" USING btree ("mobile_normalized");--> statement-breakpoint
CREATE UNIQUE INDEX "customer_mobile_unique_active" ON "customer" USING btree ("mobile_normalized") WHERE archived_at is null and mobile_normalized is not null;--> statement-breakpoint
CREATE INDEX "household_name_idx" ON "household" USING btree ("name");--> statement-breakpoint
CREATE INDEX "household_city_idx" ON "household" USING btree ("city");--> statement-breakpoint
CREATE INDEX "household_archived_idx" ON "household" USING btree ("archived_at");--> statement-breakpoint
CREATE UNIQUE INDEX "customer_preference_unique" ON "customer_preference" USING btree ("customer_id","option_id","polarity");--> statement-breakpoint
CREATE INDEX "customer_preference_customer_idx" ON "customer_preference" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "customer_preference_option_idx" ON "customer_preference" USING btree ("option_id","polarity");--> statement-breakpoint
CREATE UNIQUE INDEX "preference_option_kind_slug_unique" ON "preference_option" USING btree ("kind","slug");--> statement-breakpoint
CREATE INDEX "preference_option_kind_idx" ON "preference_option" USING btree ("kind","sort_order");--> statement-breakpoint
CREATE INDEX "preference_option_label_idx" ON "preference_option" USING btree ("label");--> statement-breakpoint
CREATE INDEX "activity_log_customer_idx" ON "activity_log" USING btree ("customer_id","created_at");--> statement-breakpoint
CREATE INDEX "activity_log_household_idx" ON "activity_log" USING btree ("household_id","created_at");--> statement-breakpoint
CREATE INDEX "activity_log_entity_idx" ON "activity_log" USING btree ("entity_type","entity_id");--> statement-breakpoint
CREATE INDEX "activity_log_created_idx" ON "activity_log" USING btree ("created_at");--> statement-breakpoint
CREATE INDEX "interaction_customer_idx" ON "interaction" USING btree ("customer_id","occurred_at");--> statement-breakpoint
CREATE INDEX "interaction_household_idx" ON "interaction" USING btree ("household_id","occurred_at");--> statement-breakpoint
CREATE INDEX "milestone_customer_idx" ON "milestone" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "milestone_household_idx" ON "milestone" USING btree ("household_id");--> statement-breakpoint
CREATE INDEX "milestone_upcoming_idx" ON "milestone" USING btree ("month_of_year","day_of_month","status");--> statement-breakpoint
CREATE INDEX "milestone_type_idx" ON "milestone" USING btree ("type");--> statement-breakpoint
CREATE INDEX "task_assignee_idx" ON "task" USING btree ("assignee_id","status");--> statement-breakpoint
CREATE INDEX "task_customer_idx" ON "task" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "task_due_idx" ON "task" USING btree ("due_date","status");
--> statement-breakpoint
-- Search support for the Client 360 command palette and the clients list.
--
-- Requirement: search by Customer Name, Customer ID, Household ID and Mobile.
-- Postgres native search is used deliberately. At Vara5's data volume a
-- dedicated search service would be infrastructure without a payoff.

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

--> statement-breakpoint

-- Weighted document per client. Names rank above city and email so a search
-- for "Delhi" never outranks a person actually called that.
ALTER TABLE "customer"
  ADD COLUMN "search_document" tsvector
  GENERATED ALWAYS AS (
    setweight(to_tsvector('simple', coalesce("first_name", '')), 'A') ||
    setweight(to_tsvector('simple', coalesce("last_name", '')), 'A') ||
    setweight(to_tsvector('simple', coalesce("preferred_name", '')), 'A') ||
    setweight(to_tsvector('simple', coalesce("ref", '')), 'B') ||
    setweight(to_tsvector('simple', coalesce("email", '')), 'C') ||
    setweight(to_tsvector('simple', coalesce("city", '')), 'D')
  ) STORED;

--> statement-breakpoint

CREATE INDEX "customer_search_document_idx"
  ON "customer" USING gin ("search_document");

--> statement-breakpoint

-- Trigram indexes carry the fuzzy half: misspelled names and partial numbers.
-- "Rishab" finds "Rishabh"; "98765" finds +91 98765 43210.
CREATE INDEX "customer_first_name_trgm_idx"
  ON "customer" USING gin ("first_name" gin_trgm_ops);

--> statement-breakpoint

CREATE INDEX "customer_last_name_trgm_idx"
  ON "customer" USING gin ("last_name" gin_trgm_ops);

--> statement-breakpoint

CREATE INDEX "customer_preferred_name_trgm_idx"
  ON "customer" USING gin ("preferred_name" gin_trgm_ops);

--> statement-breakpoint

CREATE INDEX "customer_mobile_trgm_idx"
  ON "customer" USING gin ("mobile_normalized" gin_trgm_ops);

--> statement-breakpoint

CREATE INDEX "customer_ref_trgm_idx"
  ON "customer" USING gin ("ref" gin_trgm_ops);

--> statement-breakpoint

CREATE INDEX "household_name_trgm_idx"
  ON "household" USING gin ("name" gin_trgm_ops);

--> statement-breakpoint

CREATE INDEX "household_ref_trgm_idx"
  ON "household" USING gin ("ref" gin_trgm_ops);
--> statement-breakpoint
-- The activity log is append-only, enforced in the database so no future
-- service, script or AI tool can quietly rewrite the audit trail.
--
-- DELETE is never allowed. An UPDATE is allowed only when it does nothing but
-- clear a client or household reference, because erasing a client cascades a
-- referential SET NULL onto this table and that is itself an UPDATE. What
-- happened, when, and who did it all remain immutable, and a reference may only
-- be cleared, never repointed at someone else.
CREATE OR REPLACE FUNCTION "activity_log_is_append_only"()
RETURNS trigger AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'activity_log is append-only: DELETE is not permitted';
  END IF;

  IF NEW."id" IS DISTINCT FROM OLD."id"
     OR NEW."entity_type" IS DISTINCT FROM OLD."entity_type"
     OR NEW."entity_id" IS DISTINCT FROM OLD."entity_id"
     OR NEW."action" IS DISTINCT FROM OLD."action"
     OR NEW."summary" IS DISTINCT FROM OLD."summary"
     OR NEW."changes" IS DISTINCT FROM OLD."changes"
     OR NEW."actor_id" IS DISTINCT FROM OLD."actor_id"
     OR NEW."created_at" IS DISTINCT FROM OLD."created_at"
     -- A reference may only be cleared, never repointed at someone else.
     OR (NEW."customer_id" IS NOT NULL
         AND NEW."customer_id" IS DISTINCT FROM OLD."customer_id")
     OR (NEW."household_id" IS NOT NULL
         AND NEW."household_id" IS DISTINCT FROM OLD."household_id")
  THEN
    RAISE EXCEPTION
      'activity_log is append-only: only clearing a client or household reference is permitted';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
--> statement-breakpoint
CREATE TRIGGER "activity_log_no_update"
  BEFORE UPDATE OR DELETE ON "activity_log"
  FOR EACH ROW EXECUTE FUNCTION "activity_log_is_append_only"();
--> statement-breakpoint
-- Next calendar occurrence of a recurring milestone.
--
-- Written as a database function rather than application code so the upcoming
-- lists, the dashboard counts and any future reminder job all agree on what
-- "next" means, and so the work stays inside one indexed query.
--
-- Leap-day handling: a 29 February anniversary clamps to 28 February in a
-- common year rather than erroring or disappearing from the list.

CREATE OR REPLACE FUNCTION "vara5_next_occurrence"(
  p_month int,
  p_day int,
  p_from date
)
RETURNS date
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT min(candidate)
  FROM (
    SELECT least(
             make_date(y, p_month, 1) + (p_day - 1),
             (make_date(y, p_month, 1) + interval '1 month - 1 day')::date
           ) AS candidate
    FROM (
      SELECT extract(year FROM p_from)::int + offset_years AS y
      FROM generate_series(0, 1) AS offset_years
    ) AS years
  ) AS candidates
  WHERE candidate >= p_from;
$$;

--> statement-breakpoint

-- Days remaining until a milestone's next occurrence. Null for a one-off date
-- that has already passed.
CREATE OR REPLACE FUNCTION "vara5_days_until"(
  p_month int,
  p_day int,
  p_from date
)
RETURNS int
LANGUAGE sql
IMMUTABLE
AS $$
  SELECT ("vara5_next_occurrence"(p_month, p_day, p_from) - p_from)::int;
$$;
--> statement-breakpoint
-- Close the Supabase API layer off from Blackbook's tables.
--
-- Blackbook talks to Postgres directly and does all of its authorization in the
-- service layer, which is what the handover asks for. But it shares a database
-- with a Supabase stack, and that stack runs PostgREST behind Kong: anything
-- readable in `public` is reachable over HTTP with the anon key. Client names,
-- phone numbers, home addresses and family details are exactly what must not be.
--
-- Two locks, because they cover different things.
--
-- Row-level security with no policies denies every row to every role except the
-- table owner, who bypasses RLS unless FORCE ROW LEVEL SECURITY is set. The
-- application connects as the owner, so this is invisible to it and total for
-- everyone else. Verified: a role granted ALL on a table reads 1 row before and
-- 0 after, while the owner still reads and writes.
--
-- Revoking the grants covers what RLS does not, TRUNCATE among them, and means
-- the tables are not merely empty to PostgREST but absent from it.
--
-- This depends on the application connecting as the role that owns the tables.
-- If that ever changes, it will need policies or it will see nothing at all.

DO $$
DECLARE
  target text;
BEGIN
  FOR target IN
    SELECT tablename FROM pg_tables WHERE schemaname = 'public'
  LOOP
    EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', target);
  END LOOP;
END $$;

--> statement-breakpoint

-- The Supabase roles only exist in a Supabase stack. Local development and the
-- test database have neither, so this is conditional rather than assumed.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon;
    REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM anon;
  END IF;

  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'authenticated') THEN
    REVOKE ALL ON ALL TABLES IN SCHEMA public FROM authenticated;
    REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM authenticated;
    REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM authenticated;
  END IF;
END $$;
