-- The loyalty programme catalogue, as the desk settled it.
--
-- A loyalty programme is a membership, not a taste: these rows carry a client's
-- membership number and tier on `customer_preference`, so the tiers a
-- programme actually offers belong on the option beside it. The list was built
-- from a reference export and then classified by hand, which is work that
-- cannot be repeated from the deployment: there is no host shell to run the
-- importer in, and the fuzzy matching it does against what is already stored
-- would not give the same answer twice.
--
-- So the settled result is written down here instead. Keyed on (kind, slug),
-- which is the table's own unique index, so it is safe to run against a
-- database that already holds some of these.
--
-- On a row that already exists only the tier list and the grouping move. The
-- label is left alone: a programme somebody at the desk renamed keeps the name
-- they gave it, and `is_custom` keeps saying who added it. Nothing is ever
-- deleted -- a programme a client already holds a membership in must not
-- vanish underneath them.
INSERT INTO "preference_option" ("kind", "slug", "label", "grouping", "tiers", "is_custom", "sort_order") VALUES
  ('loyalty_programme', 'aarp_rewards', 'AARP Rewards', 'Booking', '{}', false, 100),
  ('loyalty_programme', 'ana_mileage_club', 'ANA Mileage Club', 'Airline', ARRAY['Diamond','Platinum','Bronze']::text[], false, 138),
  ('loyalty_programme', 'accor_all', 'Accor ALL', 'Hotel', '{}', false, 179),
  ('loyalty_programme', 'accor_live_limitless', 'Accor Live Limitless', 'Hotel', ARRAY['Diamond','Platinum','Gold','Silver','Classic']::text[], false, 101),
  ('loyalty_programme', 'ace_rent_a_car', 'Ace Rent a Car', 'Car hire', ARRAY['Member']::text[], false, 102),
  ('loyalty_programme', 'advantage_rent_a_car', 'Advantage Rent a Car (Instant Rewards)', 'Car hire', ARRAY['Member']::text[], false, 103),
  ('loyalty_programme', 'aegean_airlines', 'Aegean Airlines (Miles & Bonus)', 'Airline', ARRAY['Gold','Silver','Blue']::text[], false, 104),
  ('loyalty_programme', 'aer_lingus', 'Aer Lingus (Gold Circle)', 'Airline', ARRAY['Concierge','Platinum','Silver','Green']::text[], false, 105),
  ('loyalty_programme', 'aerolineas_argentinas', 'Aerolineas Argentinas (Plus)', 'Airline', ARRAY['Diamond','Platinum','Gold']::text[], false, 106),
  ('loyalty_programme', 'aeroloft_bonus', 'Aeroloft Bonus', 'Airline', ARRAY['Gold','Silver']::text[], false, 107),
  ('loyalty_programme', 'aeromexico', 'Aeromexico (Club Premier)', 'Airline', ARRAY['Titanium','Platinum','Gold']::text[], false, 108),
  ('loyalty_programme', 'aeroplan_loyalty_program', 'Aeroplan Loyalty Program', 'Airline', ARRAY['Super Elite','Elite 75k','Eilte 50k','Elite 35k','Prestige 25k']::text[], false, 109),
  ('loyalty_programme', 'air_alg_rie', 'Air Algérie (Air Algérie Plus)', 'Airline', ARRAY['Fly in Card','Tahat','Chelia','Durdjuira']::text[], false, 110),
  ('loyalty_programme', 'air_arabia', 'Air Arabia (Airewards)', 'Airline', ARRAY['Member']::text[], false, 111),
  ('loyalty_programme', 'air_astana', 'Air Astana (Nomad Club)', 'Airline', ARRAY['Diamond','Gold','Silver','Blue']::text[], false, 112),
  ('loyalty_programme', 'air_austral', 'Air Austral (My Capricorne)', 'Airline', ARRAY['Subscriber','Exculsive','Premium','Essential']::text[], false, 113),
  ('loyalty_programme', 'air_baltic', 'Air Baltic (Pins)', 'Airline', ARRAY['VIP','Executive','Club']::text[], false, 114),
  ('loyalty_programme', 'air_canada_aeroplan', 'Air Canada Aeroplan', 'Airline', ARRAY['Super Elite','Elite 75k','Eilte 50k','Elite 35k','Prestige 25k']::text[], false, 115),
  ('loyalty_programme', 'air_caraibes', 'Air Caraibes (Preference)', 'Airline', ARRAY['Diamant','Gold','Silver Plus','Silver']::text[], false, 116),
  ('loyalty_programme', 'air_china', 'Air China (PhoenixMiles)', 'Airline', ARRAY['Platinum','Gold','Silver']::text[], false, 117),
  ('loyalty_programme', 'air_cote_d_ivoire', 'Air Cote D''Ivoire (sMiles)', 'Airline', ARRAY['Diamond','Five Stars','Four Stars','three Stars']::text[], false, 118),
  ('loyalty_programme', 'air_europa', 'Air Europa (SUMA)', 'Airline', ARRAY['SUMA Platinum','SUMA Gold','SUMA Silver','SUMA']::text[], false, 119),
  ('loyalty_programme', 'air_france_klm_flying_blue', 'Air France KLM Flying Blue', 'Airline', ARRAY['Platinum','Gold','Silver','Explorer']::text[], false, 173),
  ('loyalty_programme', 'air_india_maharaja_club', 'Air India Maharaja Club', 'Airline', ARRAY['The Maharaja Club','Golden Edge Club','Silver Edge Club','Base Tier']::text[], false, 175),
  ('loyalty_programme', 'air_macau', 'Air Macau (Privileges)', 'Airline', ARRAY['Platinum','Gold','Elite']::text[], false, 120),
  ('loyalty_programme', 'air_malta', 'Air Malta (Flypass)', 'Airline', ARRAY['Diamond','Permanent','Regular']::text[], false, 121),
  ('loyalty_programme', 'air_mauritius', 'Air Mauritius (Kestrelflyer)', 'Airline', ARRAY['Gold','Silver','Red']::text[], false, 122),
  ('loyalty_programme', 'air_moldova_club', 'Air Moldova Club', 'Airline', ARRAY['Exclusive','Prestige','Member']::text[], false, 123),
  ('loyalty_programme', 'air_new_zealand', 'Air New Zealand (Airpoints)', 'Airline', ARRAY['Elite','Gold','Silver']::text[], false, 124),
  ('loyalty_programme', 'air_niugini', 'Air Niugini (Destinations)', 'Airline', ARRAY['Gold','Silver','Classic']::text[], false, 125),
  ('loyalty_programme', 'air_tahiti_nui', 'Air Tahiti Nui (Club Tiare)', 'Airline', ARRAY['Gold','Silver','Tahia']::text[], false, 126),
  ('loyalty_programme', 'air_transat', 'Air Transat', 'Airline', '{}', false, 127),
  ('loyalty_programme', 'airberlin', 'AirBerlin (business points)', 'Airline', '{}', false, 128),
  ('loyalty_programme', 'alamo_insiders', 'Alamo Insiders', 'Car hire', ARRAY['Member']::text[], false, 129),
  ('loyalty_programme', 'alaska_airlines', 'Alaska Airlines (EasyBiz Corporate)', 'Airline', '{}', false, 130),
  ('loyalty_programme', 'allways_rewards', 'Allways Rewards', 'Booking', '{}', false, 131),
  ('loyalty_programme', 'amawaterways', 'AmaWaterways', 'Cruise', ARRAY['Blue','Silver','Gold']::text[], false, 132),
  ('loyalty_programme', 'americinn', 'AmericInn (Easy Rewards)', 'Hotel', ARRAY['Diamond','Platinum','Gold','Blue']::text[], false, 136),
  ('loyalty_programme', 'american_airlines_aadvantage', 'American Airlines AAdvantage', 'Airline', ARRAY['AAdvantage Gold','AAdvantage Platinum','AAdvantage Platinum Pro','AAdvantage Executive Platinum']::text[], false, 133),
  ('loyalty_programme', 'american_automative_association', 'American Automative Association (AAA)', null, ARRAY['Premier','Plus','Basic']::text[], false, 134),
  ('loyalty_programme', 'american_cruise_lines', 'American Cruise Lines', 'Cruise', '{}', false, 135),
  ('loyalty_programme', 'amtrak_guest_rewards', 'Amtrak Guest Rewards', 'Rail', ARRAY['Select Executive','Select Plus','Select','Member']::text[], false, 137),
  ('loyalty_programme', 'asiana_airlines_asiana_club', 'Asiana Airlines Asiana Club', 'Airline', ARRAY['Platinum','Diamond Plus','Diamond','Gold']::text[], false, 139),
  ('loyalty_programme', 'asky_airlines', 'Asky Airlines (ASKY Club)', 'Airline', ARRAY['Black','Gold','Silver','Brown']::text[], false, 140),
  ('loyalty_programme', 'atlas_yacht_club', 'Atlas Yacht Club', 'Cruise', ARRAY['Purple','Bronze','Silver','Gold','Captain''s Yacht Club']::text[], false, 141),
  ('loyalty_programme', 'atlasglobal', 'AtlasGlobal (AtlasMiles)', 'Airline', '{}', false, 142),
  ('loyalty_programme', 'atmos', 'Atmos (Alaska)', 'Airline', ARRAY['MVP','MVP Gold 100k','MVP Gold 75k','MVP Gold','MVP Gold 75K','MVP Gold 100K','Atmos Silver','Atmos Gold','Atmos Platinum','Atmos Titanium']::text[], false, 143),
  ('loyalty_programme', 'avianca', 'Avianca (Amigo)', 'Airline', ARRAY['Diamond','Gold','Silver','Red Plus']::text[], false, 144),
  ('loyalty_programme', 'avianca_lifemiles', 'Avianca LifeMiles', 'Airline', ARRAY['Diamond','Gold','Silver','Red Plus']::text[], false, 145),
  ('loyalty_programme', 'avios', 'Avios', 'Airline', ARRAY['Gold','Silver','Bronze','Blue']::text[], false, 146),
  ('loyalty_programme', 'avis', 'Avis (Preferred)', 'Hotel', ARRAY['President''s Club','Preferred Plus','Preferred']::text[], false, 147),
  ('loyalty_programme', 'azamara', 'Azamara (Le Club Voyage)', 'Cruise', ARRAY['Discoverer Platinum','Discoverer Plus','Discoverer','Explorer','Adventurer']::text[], false, 148),
  ('loyalty_programme', 'azerbaijan_airlines', 'Azerbaijan Airlines (Azal Miles)', 'Airline', ARRAY['Platinum','Gold','Classic']::text[], false, 149),
  ('loyalty_programme', 'azul', 'Azul (TudoAzul)', 'Airline', ARRAY['Diamond','Sapphire','Topaz','Blue']::text[], false, 150),
  ('loyalty_programme', 'bangkok_airways', 'Bangkok Airways (FlyerBonus)', 'Airline', ARRAY['Premier Plus','Premier','Priority']::text[], false, 151),
  ('loyalty_programme', 'belavia', 'Belavia (Leader)', 'Airline', ARRAY['Silver','Gold']::text[], false, 152),
  ('loyalty_programme', 'belmond_bellini', 'Belmond Bellini', 'Hotel', ARRAY['Member']::text[], false, 153),
  ('loyalty_programme', 'best_western_rewards', 'Best Western Rewards', 'Hotel', ARRAY['Diamond Select','Diamond','Platinum','Gold','Blue']::text[], false, 154),
  ('loyalty_programme', 'booking_com', 'Booking.com', 'Booking', ARRAY['Genius Level 3','Genius Level 2','Genisu Level 1']::text[], false, 155),
  ('loyalty_programme', 'borgata', 'Borgata (Rewards)', 'Hotel', ARRAY['Noir','Platinum','Gold','Pearl','Saphire']::text[], false, 156),
  ('loyalty_programme', 'braathens_regional_airlines', 'Braathens Regional Airlines (BRA Friends )', 'Airline', ARRAY['Merit','Gold','Silver']::text[], false, 157),
  ('loyalty_programme', 'breeze_airways', 'Breeze Airways', 'Airline', '{}', false, 158),
  ('loyalty_programme', 'brendan_tours', 'Brendan Tours', 'Tour operator', '{}', false, 159),
  ('loyalty_programme', 'british_airways', 'British Airways (On Business)', 'Airline', ARRAY['On 3 Elite','On 2 Elite','On 1 Elite']::text[], false, 160),
  ('loyalty_programme', 'british_airways_executive_club', 'British Airways Executive Club', 'Airline', ARRAY['Blue','Bronze','Silver','Gold']::text[], false, 172),
  ('loyalty_programme', 'brussels_airlines', 'Brussels Airlines (LOOPs)', 'Airline', '{}', false, 161),
  ('loyalty_programme', 'budget_fastbreak', 'Budget Fastbreak', 'Car hire', '{}', false, 162),
  ('loyalty_programme', 'bulgaria_air', 'Bulgaria Air (Fly More)', 'Airline', ARRAY['Gold','Silver','Basic']::text[], false, 163),
  ('loyalty_programme', 'cat', 'CAT (C-Club)', null, ARRAY['Platinum','Gold','Silver','Bronze','Blue']::text[], false, 167),
  ('loyalty_programme', 'caesar_s_rewards', 'Caesar''s Rewards', 'Hotel', ARRAY['GOLD','PLATINUM','DIAMOND','DIAMOND PLUS','DIAMOND ELITE','SEVEN STARS®']::text[], false, 164),
  ('loyalty_programme', 'caribbean_airlines', 'Caribbean Airlines (Caribbean Miles)', 'Airline', ARRAY['Executive','Gold','Silver','Bronze']::text[], false, 165),
  ('loyalty_programme', 'carnival', 'Carnival (VIFP)', 'Cruise', ARRAY['Diamond','Platinum','Gold','Red','Blue']::text[], false, 166),
  ('loyalty_programme', 'cathay_asia_miles', 'Cathay Asia Miles', 'Airline', ARRAY['Diamond','Gold','Silver','Green']::text[], false, 174),
  ('loyalty_programme', 'cayman_airways', 'Cayman Airways (Sir Turtle Rewards)', 'Airline', ARRAY['Platinum','Gold','Silver']::text[], false, 168),
  ('loyalty_programme', 'cebu_pacific', 'Cebu Pacific (Getgo)', 'Airline', ARRAY['Black','Platinum','Classic','Gold','Silver']::text[], false, 169),
  ('loyalty_programme', 'celebrity_cruises', 'Celebrity Cruises (Captain''s Club)', 'Cruise', ARRAY['Zenith','Elite Plus','Elite','Select','Classic','Preview']::text[], false, 170),
  ('loyalty_programme', 'china_airlines', 'China Airlines (Dynasty Flyer)', 'Airline', ARRAY['Paragon Membership','Emerald Membership','Gold Membership','Dynasty Membership']::text[], false, 171),
  ('loyalty_programme', 'china_eastern', 'China Eastern (Eastern Miles)', 'Airline', '{}', false, 172),
  ('loyalty_programme', 'china_southern', 'China Southern (Sky Pearl)', null, ARRAY['Platinum','Gold','Silver']::text[], false, 173),
  ('loyalty_programme', 'choice_hotels', 'Choice Hotels (Nordic Choice Club)', 'Hotel', ARRAY['Platinum','Gold','Silver','Blue']::text[], false, 174),
  ('loyalty_programme', 'choice_privileges', 'Choice Privileges', 'Hotel', ARRAY['Diamond','Platinum','Gold','Member']::text[], false, 175),
  ('loyalty_programme', 'club_carlson_hotels', 'Club Carlson Hotels', 'Hotel', ARRAY['Platinum','Gold','Silver','Club']::text[], false, 176),
  ('loyalty_programme', 'club_med', 'Club Med', 'Hotel', ARRAY['Great Member Number']::text[], false, 177),
  ('loyalty_programme', 'coast_hotels', 'Coast Hotels (Coast Rewards)', 'Hotel', ARRAY['Platinum','Gold','Silver','Purple','Pink']::text[], false, 178),
  ('loyalty_programme', 'collette_passport_club', 'Collette Passport Club', 'Tour operator', '{}', false, 179),
  ('loyalty_programme', 'contiki', 'Contiki', 'Tour operator', '{}', false, 180),
  ('loyalty_programme', 'copa_airlines_connectmiles', 'Copa Airlines ConnectMiles (Prefer)', 'Airline', ARRAY['Presidential','Platinum','Gold','Silver']::text[], false, 181),
  ('loyalty_programme', 'cosmopolitan_hotels', 'Cosmopolitan Hotels (Identity)', 'Hotel', ARRAY['Platinum','Gold','Sterling','Velvet']::text[], false, 182),
  ('loyalty_programme', 'cosmos', 'Cosmos', 'Tour operator', '{}', false, 183),
  ('loyalty_programme', 'crystal_society', 'Crystal Society', 'Cruise', ARRAY['Member']::text[], false, 184),
  ('loyalty_programme', 'cunard', 'Cunard', 'Cruise', ARRAY['Diamond','Platinum','Gold','Silver']::text[], false, 185),
  ('loyalty_programme', 'czech_airlines', 'Czech Airlines (OK Plus Corporate)', 'Airline', ARRAY['Platinum','Gold','Silver']::text[], false, 186),
  ('loyalty_programme', 'dan_hotels', 'Dan Hotels (e-dan club)', 'Hotel', ARRAY['Member']::text[], false, 187),
  ('loyalty_programme', 'delta', 'Delta (SkyBonus Corporate)', 'Airline', ARRAY['SkyBonus Elite']::text[], false, 188),
  ('loyalty_programme', 'delta_skymiles', 'Delta SkyMiles', 'Airline', ARRAY['Silver Medallion','Gold Medallion','Platinum Medallion','Diamond Medallion']::text[], false, 189),
  ('loyalty_programme', 'deutsche_bahn', 'Deutsche Bahn (BahnCard)', 'Rail', ARRAY['BahnCard 100','BahnCard 50','BahnCard 25']::text[], false, 190),
  ('loyalty_programme', 'disney_cruise_line', 'Disney Cruise Line (Castaway Club)', 'Cruise', ARRAY['Pearl','Platinum','Gold','Silver']::text[], false, 191),
  ('loyalty_programme', 'dorchester_diamond', 'Dorchester Diamond', 'Hotel', ARRAY['Member']::text[], false, 192),
  ('loyalty_programme', 'dorint', 'Dorint (Card)', 'Hotel', ARRAY['Card Premium','Card']::text[], false, 193),
  ('loyalty_programme', 'e_z_rent_a_car', 'E-Z Rent-A-Car (E-Z Money)', 'Car hire', '{}', false, 194),
  ('loyalty_programme', 'el_al_israel_airlines', 'EL AL Israel Airlines (Matmid)', 'Airline', ARRAY['TopPlatinum','Platinum','Gold','Silver','Matmid']::text[], false, 197),
  ('loyalty_programme', 'easyjet', 'Easyjet', 'Airline', ARRAY['Member']::text[], false, 195),
  ('loyalty_programme', 'egypt_air_plusfriends', 'Egypt Air PlusFriends)', 'Airline', ARRAY['PLATINUM','ELITE','GOLD','SILVER','BLUE']::text[], false, 196),
  ('loyalty_programme', 'elite_hotels_of_sweden', 'Elite Hotels of Sweden', 'Hotel', ARRAY['Platinum','Gold','Silver','Bronze']::text[], false, 198),
  ('loyalty_programme', 'emerald', 'Emerald', 'Cruise', ARRAY['Gold','Diamond','Emerald','Chairman''s Club']::text[], false, 199),
  ('loyalty_programme', 'emirates_skywards', 'Emirates Skywards', 'Airline', ARRAY['Platinum Medallion','Gold','Silver','Blue']::text[], false, 167),
  ('loyalty_programme', 'emirates_for_kids', 'Emirates for Kids (Skysurfer)', 'Airline', ARRAY['Gold','Silver']::text[], false, 200),
  ('loyalty_programme', 'enterprise_rent_a_car', 'Enterprise Rent-A-Car', 'Car hire', ARRAY['Platinum','Gold','Silver','Plus']::text[], false, 201),
  ('loyalty_programme', 'era_alaska', 'Era Alaska (FlyAway Rewards)', 'Airline', ARRAY['MVP Gold 100k','MVP Gold 75k','MVP Gold','MVP']::text[], false, 202),
  ('loyalty_programme', 'ethiopian_airlines', 'Ethiopian Airlines (ShebaMiles)', 'Airline', ARRAY['Platinum','Gold','Silver','Blue']::text[], false, 203),
  ('loyalty_programme', 'etihad_airways', 'Etihad Airways (Etihad Guest)', 'Airline', ARRAY['Platinum','Gold','Silver','Bronze']::text[], false, 204),
  ('loyalty_programme', 'etihad_guest', 'Etihad Guest', 'Airline', ARRAY['Member']::text[], false, 170),
  ('loyalty_programme', 'eurostar_frequent_traveler', 'Eurostar Frequent Traveler', 'Rail', ARRAY['Carte Blanche','Avantage','Classique']::text[], false, 205),
  ('loyalty_programme', 'eurowings', 'Eurowings (Boomerang)', 'Airline', ARRAY['Member']::text[], false, 206),
  ('loyalty_programme', 'eva_air', 'Eva Air (Infinity MileageLands)', 'Airline', ARRAY['Diamond','Gold','Silver','Green']::text[], false, 207),
  ('loyalty_programme', 'expedia_one_key', 'Expedia One Key', 'Booking', ARRAY['Blue','Silver','Gold','Platinum']::text[], false, 208),
  ('loyalty_programme', 'explora_club', 'Explora Club', 'Cruise', ARRAY['Classic','Silver','Gold','Platinum','Diamond']::text[], false, 209),
  ('loyalty_programme', 'fairmont_president_s_club', 'Fairmont President''s Club', 'Hotel', ARRAY['Diamond','Platinum','Gold','Silver','Classic']::text[], false, 210),
  ('loyalty_programme', 'finnair_plus', 'Finnair Plus', 'Airline', ARRAY['Finnair Plus Lifetime','Finnair Plus Platinum Lumo','Finnair Plus Platinum','Finnair Plus Gold','Finnair Plus Silver','Finnair Plus Basic']::text[], false, 211),
  ('loyalty_programme', 'first_hotels', 'First Hotels (First Member)', 'Hotel', ARRAY['Black','Platinum','Gold','Silver']::text[], false, 212),
  ('loyalty_programme', 'flybe', 'Flybe (Rewards4all)', 'Airline', '{}', false, 213),
  ('loyalty_programme', 'flynas', 'Flynas (NaSmiles)', 'Airline', ARRAY['Prime','Basic']::text[], false, 214),
  ('loyalty_programme', 'four_seasons_preferred', 'Four Seasons Preferred', 'Hotel', ARRAY['Member']::text[], false, 215),
  ('loyalty_programme', 'fox_rent_a_car', 'Fox Rent A Car (Rewards)', 'Car hire', ARRAY['Tango Card']::text[], false, 216),
  ('loyalty_programme', 'frasers_hospitality', 'Frasers Hospitality (Fraser World)', 'Hotel', ARRAY['Diamond','Sapphire','Crystal']::text[], false, 217),
  ('loyalty_programme', 'frontier_earlyreturns', 'Frontier EarlyReturns', 'Airline', ARRAY['Elite 100k','Elite 50k','Elite 20k']::text[], false, 218),
  ('loyalty_programme', 'future_inns', 'Future Inns (Rewards Club)', 'Hotel', ARRAY['Member']::text[], false, 219),
  ('loyalty_programme', 'gha_discovery', 'GHA Discovery', 'Hotel', ARRAY['Titanium','Platinum','Gold','Silver']::text[], false, 222),
  ('loyalty_programme', 'gtr_trafalgar', 'GTR Trafalgar', 'Tour operator', '{}', false, 226),
  ('loyalty_programme', 'garuda', 'Garuda (Frequent Flyer)', 'Airline', ARRAY['Platinum','Gold','Silver','Blue']::text[], false, 220),
  ('loyalty_programme', 'gate_1_travel', 'Gate 1 Travel', 'Tour operator', '{}', false, 221),
  ('loyalty_programme', 'gloria_hotels_and_resorts', 'Gloria Hotels & Resorts (Gloria Partner)', 'Hotel', ARRAY['Glorian Platinum','Glorian Diamond','Glorian Gold']::text[], false, 223),
  ('loyalty_programme', 'gol_airlines', 'Gol Airlines (Smiles)', 'Airline', ARRAY['Diamond','Gold','Silver']::text[], false, 224),
  ('loyalty_programme', 'golden_circle', 'Golden Circle', 'Hotel', ARRAY['Polaris','Diamond','Jade','Gold']::text[], false, 225),
  ('loyalty_programme', 'gulf_air', 'Gulf Air (Falconflyer)', 'Airline', ARRAY['Black','Gold','Silver','Blue']::text[], false, 227),
  ('loyalty_programme', 'hx_expeditions', 'HX Expeditions', 'Cruise', ARRAY['Bronze','Silver','Gold','Platinum']::text[], false, 238),
  ('loyalty_programme', 'hx_explorer', 'HX Explorer', null, '{}', false, 239),
  ('loyalty_programme', 'hainan_airlines', 'Hainan Airlines (Fortune Wings)', 'Airline', ARRAY['Platinum','Gold','Silver','Select','Fortune Wings']::text[], false, 228),
  ('loyalty_programme', 'hawaiian_airlines_hawaiianmiles', 'Hawaiian Airlines HawaiianMiles', 'Airline', ARRAY['Member','Pualani Gold','Pualani Platinum']::text[], false, 229),
  ('loyalty_programme', 'hertz_gold_plus_rewards', 'Hertz Gold Plus Rewards', 'Car hire', ARRAY['President''s Circle','Hertz Five Star','Gold']::text[], false, 230),
  ('loyalty_programme', 'hilton_grand_vacations', 'Hilton Grand Vacations (Club)', 'Hotel', ARRAY['Hilton Honors Points','Bonus Points','ClubPoints']::text[], false, 231),
  ('loyalty_programme', 'hilton_honors', 'Hilton Honors', 'Hotel', ARRAY['Diamond','Gold','Silver','Member','Diamond Reserve']::text[], false, 177),
  ('loyalty_programme', 'holland_america_line', 'Holland America Line (Mariner Society)', 'Cruise', ARRAY['5 Star Mariner','4 Star Mariner','3 Star Mariner','2 Star Mariner','Star Mariner']::text[], false, 232),
  ('loyalty_programme', 'hostelworld', 'Hostelworld (My World)', 'Hotel', ARRAY['Member']::text[], false, 233),
  ('loyalty_programme', 'hotelclub', 'HotelClub (Member Rewards)', 'Hotel', ARRAY['Diamond','Platinum','Gold','Silver']::text[], false, 235),
  ('loyalty_programme', 'hotelbooker_org', 'Hotelbooker.org', 'Hotel', '{}', false, 234),
  ('loyalty_programme', 'hotels_com_rewardsmileage_club', 'Hotels.com RewardsMileage Club)', 'Hotel', ARRAY['Gold','Silver']::text[], false, 236),
  ('loyalty_programme', 'hurtigruten_1893_ambassador_program', 'Hurtigruten - 1893 Ambassador Program', 'Cruise', '{}', false, 237),
  ('loyalty_programme', 'hyatt', 'Hyatt (Vacation Club)', 'Hotel', ARRAY['Diamond','Platinum','Gold','Silver','Bronze','Copper','Mountain']::text[], false, 240),
  ('loyalty_programme', 'i_prefer_hotel_rewards', 'I Prefer Hotel Rewards', 'Hotel', ARRAY['Elite','Explorer','Insider']::text[], false, 241),
  ('loyalty_programme', 'ihg_one_rewards', 'IHG One Rewards', 'Hotel', ARRAY['Diamon Elite','Platinum Elite','Gold Elite','Silver Elite','Club']::text[], false, 180),
  ('loyalty_programme', 'iberia_plus', 'Iberia Plus', 'Airline', ARRAY['Infinite Prime','Infinite','Platinum','Gold','Silver','Classic']::text[], false, 242),
  ('loyalty_programme', 'icelandair', 'Icelandair (Saga Club)', 'Airline', ARRAY['Gold','Silver']::text[], false, 243),
  ('loyalty_programme', 'indigo', 'IndiGo', 'Airline', ARRAY['Member']::text[], false, 244),
  ('loyalty_programme', 'insight_vacations', 'Insight Vacations', 'Tour operator', '{}', false, 245),
  ('loyalty_programme', 'invited', 'Invited', 'Hotel', ARRAY['Indulged','Inspired','Intrigued']::text[], false, 246),
  ('loyalty_programme', 'island_air', 'Island Air (Cloud 9)', 'Airline', '{}', false, 247),
  ('loyalty_programme', 'jal_hotels', 'JAL Hotels (One Harmony)', 'Hotel', ARRAY['Exclusive','Loyal','Member']::text[], false, 248),
  ('loyalty_programme', 'japan_airlines', 'Japan Airlines (JMB)', 'Airline', ARRAY['Diamond','Premier','Sapphire','Crystal']::text[], false, 249),
  ('loyalty_programme', 'jet2_com', 'Jet2.com (My Jet2)', 'Airline', ARRAY['Member']::text[], false, 250),
  ('loyalty_programme', 'jetblue_airways', 'JetBlue Airways (CompanyBlue)', 'Airline', ARRAY['Mint','Blue Extra','Blue Plus','Blue','Blue Basic']::text[], false, 251),
  ('loyalty_programme', 'jetblue_trueblue', 'JetBlue TrueBlue', 'Airline', ARRAY['Member','Mosaic']::text[], false, 252),
  ('loyalty_programme', 'jin_jiang_group', 'Jin Jiang Group (J-Club)', 'Hotel', ARRAY['V3 Gold','V2 Silver','V1 Classic','V4 Platinum']::text[], false, 253),
  ('loyalty_programme', 'jinling_hotels', 'Jinling Hotels (Elite)', 'Hotel', ARRAY['Platinum','Gold','Elite']::text[], false, 254),
  ('loyalty_programme', 'jumeirah', 'Jumeirah (Sirius)', 'Hotel', ARRAY['Platinum','Gold','Silver','Member']::text[], false, 255),
  ('loyalty_programme', 'jurys_inn', 'Jurys Inn (Jurys Rewards)', 'Hotel', ARRAY['Floor 3','Floor 2','Floor 1']::text[], false, 256),
  ('loyalty_programme', 'klm_bluebiz', 'KLM BlueBiz (Corporate)', 'Airline', ARRAY['Member']::text[], false, 259),
  ('loyalty_programme', 'keystone_tours', 'Keystone Tours', 'Tour operator', '{}', false, 257),
  ('loyalty_programme', 'kimpton', 'Kimpton (Karma Rewards)', 'Hotel', ARRAY['Inner Circle','Diamond Elite','Platinum Elite','Gold Elite','Silver Elite','Club']::text[], false, 258),
  ('loyalty_programme', 'korean_air', 'Korean Air (SkyPass)', 'Airline', ARRAY['Million Miler Club','Morning Calm Premium Club','Morning Calm Club']::text[], false, 260),
  ('loyalty_programme', 'kuwait_airways', 'Kuwait Airways (Oasis Club)', 'Airline', ARRAY['Platinum','Gold','Silver','Blue']::text[], false, 261),
  ('loyalty_programme', 'latam', 'LATAM (LATAM Pass)', 'Airline', ARRAY['Black Signature','Black','Platinum','Gold Plus','Gold']::text[], false, 265),
  ('loyalty_programme', 'la_compagnie', 'La Compagnie (My Compagnie)', 'Airline', ARRAY['FLEX','SMART','PROMO']::text[], false, 262),
  ('loyalty_programme', 'la_quinta', 'La Quinta', 'Hotel', ARRAY['Diamond','Platinum','Gold','Blue']::text[], false, 263),
  ('loyalty_programme', 'langham_hotels', 'Langham Hotels (1865 Club)', 'Hotel', ARRAY['Destiny','Voyager','Gateway','Explorer']::text[], false, 264),
  ('loyalty_programme', 'leaders_club', 'Leaders Club', 'Hotel', ARRAY['Sterling','Clud']::text[], false, 266),
  ('loyalty_programme', 'leading_hotels_of_the_world', 'Leading Hotels of the World (Leaders Club)', 'Hotel', ARRAY['Sterling','Club']::text[], false, 267),
  ('loyalty_programme', 'leonardo_hotels', 'Leonardo Hotels (AdvantageCLUB)', 'Hotel', ARRAY['Member']::text[], false, 268),
  ('loyalty_programme', 'lindblad_expeditions', 'Lindblad Expeditions', 'Cruise', '{}', false, 269),
  ('loyalty_programme', 'localiza_rent_a_car', 'Localiza Rent a Car', 'Car hire', ARRAY['Platinum Card','Gold Card','Green Card']::text[], false, 270),
  ('loyalty_programme', 'luxury_gold', 'Luxury Gold', 'Tour operator', '{}', false, 271),
  ('loyalty_programme', 'mgm_resorts', 'MGM Resorts (M life Players Club)', 'Hotel', ARRAY['NOIR','Platinum','Gold','Pearl','Sapphire']::text[], false, 278),
  ('loyalty_programme', 'msc_voyagers_club', 'MSC Voyagers Club', 'Cruise', ARRAY['Classic','Silver','Gold','Diamond']::text[], false, 284),
  ('loyalty_programme', 'macdonald_hotels', 'Macdonald Hotels (The Club)', 'Hotel', '{}', false, 272),
  ('loyalty_programme', 'malaysia_airlines', 'Malaysia Airlines (Enrich)', 'Airline', ARRAY['Platinum','Gold','Silver','Blue']::text[], false, 273),
  ('loyalty_programme', 'mandarin_oriental_fan', 'Mandarin Oriental Fan', 'Hotel', ARRAY['Member']::text[], false, 274),
  ('loyalty_programme', 'marriott_bonvoy', 'Marriott Bonvoy', 'Hotel', ARRAY['Ambassador Elite','Titanium Elite','Platinum Elite','Gold Elite','Silver Elite']::text[], false, 176),
  ('loyalty_programme', 'marriott_gift_cards', 'Marriott Gift Cards', 'Hotel', ARRAY['Gift Card']::text[], false, 275),
  ('loyalty_programme', 'melia', 'Melia (Melia Rewards)', 'Hotel', ARRAY['Platinum','Gold','Silver','White']::text[], false, 276),
  ('loyalty_programme', 'meridiana_fly', 'Meridiana Fly (Hi-Fly)', 'Airline', '{}', false, 277),
  ('loyalty_programme', 'middle_east_airlines', 'Middle East Airlines (Cedar Miles)', 'Airline', ARRAY['Platinum','Gold','Silver','Blue']::text[], false, 279),
  ('loyalty_programme', 'miles_and_more', 'Miles and More', 'Airline', ARRAY['Hon Circle Members','Senator','Frequent Traveller']::text[], false, 171),
  ('loyalty_programme', 'millennium_and_copthorne', 'Millennium & Copthorne (My Millennium)', 'Hotel', ARRAY['Prestige','member']::text[], false, 280),
  ('loyalty_programme', 'moby_lines', 'Moby Lines (Moby Club)', 'Cruise', ARRAY['Member']::text[], false, 281),
  ('loyalty_programme', 'monarch', 'Monarch (Vantage Club)', 'Airline', ARRAY['ROYAL DIAMOND','SAPPHIRE','EMERALD','RUBY','MONARCH']::text[], false, 282),
  ('loyalty_programme', 'montenegro_airlines', 'Montenegro Airlines (Vision Team)', 'Airline', '{}', false, 283),
  ('loyalty_programme', 'my_europcar', 'My Europcar (Privilege)', 'Car hire', ARRAY['Elite VIP','Elite','Executive','Club']::text[], false, 285),
  ('loyalty_programme', 'nh_hotels', 'NH Hotels (NH World)', 'Hotel', ARRAY['Titanium','Platinum','Gold','Silver']::text[], false, 289),
  ('loyalty_programme', 'national', 'National (Emerald Club)', 'Cruise', ARRAY['Executive Elite','Executive','Emerald Club']::text[], false, 286),
  ('loyalty_programme', 'national_geographic', 'National Geographic', 'Tour operator', '{}', false, 287),
  ('loyalty_programme', 'new_otani', 'New Otani (Club International)', 'Hotel', ARRAY['Member']::text[], false, 288),
  ('loyalty_programme', 'nordavia', 'Nordavia (Golden Mile)', 'Airline', '{}', false, 290),
  ('loyalty_programme', 'norwegian_cruise_line', 'Norwegian Cruise Line (Latitudes)', 'Cruise', ARRAY['Ambassador','Diamond','Sapphire','Platinum','Gold','Silver','Bronze']::text[], false, 291),
  ('loyalty_programme', 'oberoi_one', 'Oberoi One', 'Hotel', ARRAY['Oberoi One']::text[], false, 182),
  ('loyalty_programme', 'oceania_cruise_lines', 'Oceania Cruise Lines', 'Cruise', ARRAY['President','Diamond','Platinum','Gold','silver','Bronze','Blue']::text[], false, 292),
  ('loyalty_programme', 'oman_air', 'Oman Air (Sindbad)', 'Airline', ARRAY['Gold','Silver','Blue']::text[], false, 293),
  ('loyalty_programme', 'omni_select_guest', 'Omni Select Guest', 'Hotel', ARRAY['Black','Platinum','Gold']::text[], false, 294),
  ('loyalty_programme', 'opinion_miles_club', 'Opinion Miles Club', 'Airline', ARRAY['Diamond','Platinum','Gold','Silver','Bronze']::text[], false, 295),
  ('loyalty_programme', 'otel_com', 'Otel.com (FivePlus)', 'Car hire', '{}', false, 296),
  ('loyalty_programme', 'p_and_o_uk_peninsular_club', 'P&O UK Peninsular Club', 'Hotel', ARRAY['Pacific Tier','Atlantic Tier','Mediterranean Tier','Caribbean Tier','Baltic Tier','Ligurian Tier']::text[], false, 297),
  ('loyalty_programme', 'pia', 'PIA (Awards Plus)', null, ARRAY['Diamond','Sapphire','Emerald']::text[], false, 305),
  ('loyalty_programme', 'paradores', 'Paradores (Amigos de Paradores)', 'Hotel', ARRAY['Circle','Gold Card','Friend']::text[], false, 298),
  ('loyalty_programme', 'park_n_go', 'Park-N-Go (Frequent Parker Rewards)', 'Car hire', ARRAY['Member']::text[], false, 299),
  ('loyalty_programme', 'payless_car_rental', 'Payless Car Rental (Perks Club)', 'Car hire', ARRAY['member']::text[], false, 300),
  ('loyalty_programme', 'pegasus_airlines', 'Pegasus Airlines (Pegasus Plus)', 'Airline', '{}', false, 301),
  ('loyalty_programme', 'peninsula_penbellini', 'Peninsula PenBellini', 'Hotel', ARRAY['Member']::text[], false, 302),
  ('loyalty_programme', 'pestana_priority_guest', 'Pestana Priority Guest', 'Hotel', ARRAY['Honor','Elite Plus','Elite','Guest']::text[], false, 303),
  ('loyalty_programme', 'philippine_airlines', 'Philippine Airlines (Mabuhay Miles)', 'Airline', ARRAY['Million Miler','Premier Elite','Elite']::text[], false, 304),
  ('loyalty_programme', 'ponant', 'Ponant', 'Cruise', ARRAY['Major','Admiral','Grand Admiral','Level #4','Commodore']::text[], false, 306),
  ('loyalty_programme', 'porter', 'Porter (VIPorter)', 'Airline', ARRAY['First','Ascent','Venture','Passport','Member']::text[], false, 307),
  ('loyalty_programme', 'preferred_hotels', 'Preferred Hotels', 'Hotel', ARRAY['Elite','Explorer','Insider']::text[], false, 308),
  ('loyalty_programme', 'premier_hotels', 'Premier Hotels (Premier Club)', 'Hotel', '{}', false, 309),
  ('loyalty_programme', 'prince_resorts_hawaii', 'Prince Resorts Hawaii (Prince Preferred)', 'Hotel', ARRAY['Ilima','Pikake','Prince Preferred']::text[], false, 310),
  ('loyalty_programme', 'princess_cruise_lines', 'Princess Cruise Lines (Captain Circle)', 'Cruise', ARRAY['Elite','Platinum','Ruby','Gold']::text[], false, 311),
  ('loyalty_programme', 'qantas', 'Qantas (Aquire)', 'Airline', ARRAY['Lifetime','Platinum','Gold','Silver']::text[], false, 312),
  ('loyalty_programme', 'qatar_privilege_club', 'Qatar Privilege Club', 'Airline', ARRAY['Platinum','Gold','Silver','Burgundy']::text[], false, 168),
  ('loyalty_programme', 'qubus_hotel', 'Qubus Hotel (Q-Club)', 'Hotel', '{}', false, 313),
  ('loyalty_programme', 'riu_hotels_and_resorts', 'RIU Hotels & Resorts (RIU Class)', 'Hotel', ARRAY['Diamond','Gold','Classic']::text[], false, 321),
  ('loyalty_programme', 'rzd', 'RZD (Bonus)', null, ARRAY['Member']::text[], false, 329),
  ('loyalty_programme', 'radisson_rewards', 'Radisson Rewards', 'Hotel', ARRAY['VIP','Premium','Club']::text[], false, 314),
  ('loyalty_programme', 'red_lion', 'Red Lion (Hello Rewards)', 'Hotel', ARRAY['Basic']::text[], false, 315),
  ('loyalty_programme', 'red_roof_inn', 'Red Roof Inn (RediCard)', 'Hotel', ARRAY['Member']::text[], false, 316),
  ('loyalty_programme', 'regal_hotels', 'Regal Hotels (Regal Rewards)', 'Hotel', ARRAY['Platinum','Gold','Classic']::text[], false, 317),
  ('loyalty_programme', 'regent_cruise_line', 'Regent Cruise Line', 'Cruise', ARRAY['Commodore','Diamond','Titanium','Platinum','Gold','silver','Bronze']::text[], false, 318),
  ('loyalty_programme', 'relais_and_chateaux_5c', 'Relais and Chateaux 5C', 'Hotel', '{}', false, 319),
  ('loyalty_programme', 'repeat_guest', 'Repeat Guest', 'Hotel', '{}', false, 320),
  ('loyalty_programme', 'riverside', 'Riverside', 'Cruise', '{}', false, 322),
  ('loyalty_programme', 'royal_air_maroc', 'Royal Air Maroc (Safar Flyer)', 'Airline', ARRAY['Platinum','Gold','Silver','Blue']::text[], false, 323),
  ('loyalty_programme', 'royal_brunei_airlines', 'Royal Brunei Airlines (Royal Skies)', 'Airline', ARRAY['Gold','Silver','Blue']::text[], false, 324),
  ('loyalty_programme', 'royal_caribbean', 'Royal Caribbean (Crown & Anchor Society)', 'Cruise', ARRAY['Pinnacle Club','Diamond Plus','Diamond','Emerald Club','Platinum','Gold']::text[], false, 325),
  ('loyalty_programme', 'royal_jordanian_airlines', 'Royal Jordanian Airlines (Royal Plus)', 'Airline', ARRAY['Platinum HAWK','Gold SPARROW','Silver JAY','Bronze SUNBIRD']::text[], false, 326),
  ('loyalty_programme', 'ryanairshaftsbury', 'RyanairShaftsbury (Premier Club)', 'Airline', ARRAY['Platinum','Gold','Silver']::text[], false, 327),
  ('loyalty_programme', 'rydges', 'Rydges (PriorityGUEST)', 'Hotel', ARRAY['Black','Platinum','Gold']::text[], false, 328),
  ('loyalty_programme', 's7_priority', 'S7 Priority', null, ARRAY['Tinkoff Premium','Tinkoff Card']::text[], false, 330),
  ('loyalty_programme', 'sncf', 'SNCF (Voyageur)', 'Rail', ARRAY['Premium Grand Voyageur','Grand Voyageur']::text[], false, 345),
  ('loyalty_programme', 'sandals_select_guest', 'Sandals Select Guest (SSG)', 'Hotel', ARRAY['Ambassador','Pearl','Diamond','EMERALD','SAPPHIRE','Coral','Select','Member']::text[], false, 331),
  ('loyalty_programme', 'santos_hotels', 'Santos Hotels (Club Santos)', 'Hotel', ARRAY['Member']::text[], false, 332),
  ('loyalty_programme', 'saudi_arabian_airlines', 'Saudi Arabian Airlines (Alfursan)', 'Airline', ARRAY['Gold “Elite Plus”','Silver “Elite”','Blue']::text[], false, 333),
  ('loyalty_programme', 'scandic_hotels', 'Scandic Hotels (Scandic Friends)', 'Hotel', ARRAY['RED LEVEL','TOP LEVEL','LEVEL 3','LEVEL 2','LEVEL 1']::text[], false, 334),
  ('loyalty_programme', 'scandinavian_airlines_system', 'Scandinavian Airlines System (EuroBonus)', 'Airline', ARRAY['Diamond','Gold','Silver','Member']::text[], false, 335),
  ('loyalty_programme', 'scenic', 'Scenic', 'Cruise', ARRAY['Gold','Diamond','Emerald','Chairman''s Club']::text[], false, 336),
  ('loyalty_programme', 'seadream_yacht_club', 'SeaDream Yacht Club', 'Cruise', ARRAY['Member']::text[], false, 338),
  ('loyalty_programme', 'seabourn_cruise_line', 'Seabourn Cruise Line', 'Cruise', ARRAY['Diamond Elite','Diamond','Platinum','Gold','Silver','Member']::text[], false, 337),
  ('loyalty_programme', 'silver_cloud', 'Silver Cloud (Rewards)', 'Hotel', ARRAY['Member']::text[], false, 339),
  ('loyalty_programme', 'silversea_venetian', 'Silversea Venetian', 'Cruise', ARRAY['Member']::text[], false, 340),
  ('loyalty_programme', 'singapore_krisflyer', 'Singapore KrisFlyer', 'Airline', ARRAY['KrisFlyer Elite Gold','KrisFlyer Elite Silver','KrisFlyer']::text[], false, 169),
  ('loyalty_programme', 'sino_hotel_group', 'Sino Hotel Group (IPrestige)', 'Hotel', ARRAY['Emerald','Amber','Crystal']::text[], false, 341),
  ('loyalty_programme', 'sirius', 'Sirius', 'Hotel', ARRAY['Gold','Silver','Blue']::text[], false, 342),
  ('loyalty_programme', 'sixt_rent_a_car', 'Sixt Rent-a-Car', 'Car hire', ARRAY['Diamond','Platinum','Gold']::text[], false, 343),
  ('loyalty_programme', 'small_luxury_hotels', 'Small Luxury Hotels (The Club)', 'Hotel', ARRAY['Indulged status','Inspired status','Intrigued status']::text[], false, 344),
  ('loyalty_programme', 'sonesta_travel_pass', 'Sonesta Travel Pass', 'Hotel', ARRAY['Elite','Preferred','Member']::text[], false, 346),
  ('loyalty_programme', 'south_african_airways', 'South African Airways (Voyager)', 'Cruise', ARRAY['Lifetime Platinum','Platinum','Gold','Silver','Blue']::text[], false, 347),
  ('loyalty_programme', 'southwest_rapid_rewards', 'Southwest Rapid Rewards', 'Airline', ARRAY['A-List','A-List Preferred','Companion Pass']::text[], false, 348),
  ('loyalty_programme', 'spirit_airlines_free_spirit', 'Spirit Airlines Free Spirit', 'Airline', ARRAY['Gold','Silver']::text[], false, 349),
  ('loyalty_programme', 'srilankan', 'SriLankan (FlySmiLes)', 'Airline', ARRAY['Platinum','Gold','Classic','Silver']::text[], false, 350),
  ('loyalty_programme', 'star_alliance_company', 'Star Alliance Company (PlusAwards)', 'Airline', ARRAY['Silver','Gold']::text[], false, 351),
  ('loyalty_programme', 'starwood_hotels', 'Starwood Hotels (Preferred Business)', 'Hotel', ARRAY['member']::text[], false, 352),
  ('loyalty_programme', 'stash_hotel_rewards', 'Stash Hotel Rewards', 'Hotel', ARRAY['Stash Plus','Member']::text[], false, 353),
  ('loyalty_programme', 'stena_line', 'Stena Line (Extra)', 'Cruise', ARRAY['Gold','Blue']::text[], false, 354),
  ('loyalty_programme', 'sun_country_rewards', 'Sun Country Rewards', 'Airline', ARRAY['Member']::text[], false, 355),
  ('loyalty_programme', 'swissotel_circlecopthorne', 'Swissotel CircleCopthorne (My Millennium)', 'Airline', ARRAY['Prestige','member']::text[], false, 356),
  ('loyalty_programme', 'taag_angola_airlines', 'TAAG Angola Airlines (Umbi Umbi Club)', 'Airline', ARRAY['Gold','Silver','Classic']::text[], false, 357),
  ('loyalty_programme', 'tap_portugal', 'TAP Portugal (Victoria Miles)', 'Airline', ARRAY['Gold','Silver']::text[], false, 359),
  ('loyalty_programme', 'tuifly_com', 'TUIfly.com', 'Airline', '{}', false, 370),
  ('loyalty_programme', 'tablethotels', 'TabletHotels (Reward Dollars)', 'Hotel', ARRAY['Member']::text[], false, 358),
  ('loyalty_programme', 'taj_innercircle', 'Taj InnerCircle', 'Hotel', ARRAY['Platinum','Gold','Silver','Copper']::text[], false, 181),
  ('loyalty_programme', 'thai_airways', 'Thai Airways (Royal Orchid Plus)', 'Airline', ARRAY['Platinum','Gold','Silver','Basic']::text[], false, 360),
  ('loyalty_programme', 'thalys', 'Thalys (The Card)', 'Rail', ARRAY['Club Plus','Club','Explorer']::text[], false, 361),
  ('loyalty_programme', 'the_montcalm_and_shaftsbury', 'The Montcalm & Shaftsbury (Premier Club)', 'Hotel', ARRAY['Platinum','Gold','Silver','Classic']::text[], false, 362),
  ('loyalty_programme', 'thon_hotels', 'Thon Hotels (Thon Member)', 'Hotel', ARRAY['Black','Platinum','Gold']::text[], false, 363),
  ('loyalty_programme', 'thrifty', 'Thrifty (Blue Chip Rewards)', 'Car hire', '{}', false, 364),
  ('loyalty_programme', 'trenitalia', 'Trenitalia (FrecciaClub)', 'Rail', ARRAY['Member']::text[], false, 365),
  ('loyalty_programme', 'trident_hotels', 'Trident Hotels (Trident Privilege)', 'Hotel', ARRAY['Platinum','Gold','Silver','RED LEVEL']::text[], false, 366),
  ('loyalty_programme', 'tripadvisor', 'TripAdvisor', 'Booking', ARRAY['Member']::text[], false, 367),
  ('loyalty_programme', 'trump_card', 'Trump Card (Privileges Program)', 'Hotel', ARRAY['Platinum','Gold','Privilege']::text[], false, 368),
  ('loyalty_programme', 'tsogo_sun', 'Tsogo Sun (Frequent Guest)', 'Hotel', ARRAY['Black','Platinum','Gold']::text[], false, 369),
  ('loyalty_programme', 'tunisair', 'Tunisair (Fidelys)', 'Airline', ARRAY['Gold','Silver','Classic']::text[], false, 371),
  ('loyalty_programme', 'turkish_airlines', 'Turkish Airlines (Miles&Smiles)', 'Airline', ARRAY['Elite Plus','Elite','Classic Plus','Classic']::text[], false, 372),
  ('loyalty_programme', 'utair', 'UTair (Status)', 'Airline', ARRAY['Gold','Silver','Bronze','Basic']::text[], false, 377),
  ('loyalty_programme', 'ukraine_international_airlines', 'Ukraine International Airlines (Panorama Club)', 'Airline', ARRAY['Elite','Premier','Classic']::text[], false, 373),
  ('loyalty_programme', 'united_mileageplus', 'United MileagePlus', 'Airline', ARRAY['Premier Silver','Premier Gold','Premier Platinum','Premier 1K','Global Services']::text[], false, 374),
  ('loyalty_programme', 'united_perksplus', 'United PerksPlus (Corporate Program)', 'Airline', ARRAY['Gold','Silver']::text[], false, 375),
  ('loyalty_programme', 'ural_airlines', 'Ural Airlines (Wings)', 'Airline', ARRAY['Gold','Silver','Blue']::text[], false, 376),
  ('loyalty_programme', 'uzbekistan_airways', 'Uzbekistan Airways (UzAirPlus)', 'Airline', ARRAY['Gold','Silver','Premium']::text[], false, 378),
  ('loyalty_programme', 'via_rail_canada', 'VIA Rail Canada (VIA Preference)', 'Rail', ARRAY['Premier','Privilege','Preference']::text[], false, 379),
  ('loyalty_programme', 'voil_hotel_rewardsiprefer', 'VOILÀ Hotel RewardsiPrefer)', 'Hotel', ARRAY['Platinum','Gold','Silver']::text[], false, 386),
  ('loyalty_programme', 'vietnam_airlines', 'Vietnam Airlines (Golden Lotus Plus)', 'Airline', ARRAY['SILVER','TITANIUM','GOLD','PLATINUM','MILLION MILER']::text[], false, 380),
  ('loyalty_programme', 'viking_cruises', 'Viking Cruises', 'Cruise', '{}', false, 381),
  ('loyalty_programme', 'virgin_atlantic_flying_club', 'Virgin Atlantic Flying Club', 'Airline', ARRAY['Gold','Silver','Red']::text[], false, 382),
  ('loyalty_programme', 'virgin_australia', 'Virgin Australia (Velocity Frequent Flyer)', 'Airline', ARRAY['Platinum','Gold','Silver','Member']::text[], false, 383),
  ('loyalty_programme', 'virgin_voyages_sailing_club', 'Virgin Voyages Sailing Club', 'Airline', ARRAY['Sea-Blazers','Sea-Rovers']::text[], false, 384),
  ('loyalty_programme', 'vistara', 'Vistara (Vistara Club)', 'Airline', ARRAY['Platinum','Gold','Silver','Base']::text[], false, 385),
  ('loyalty_programme', 'vueling_airlines', 'Vueling Airlines (Punto Punto)', 'Airline', '{}', false, 387),
  ('loyalty_programme', 'westjet', 'WestJet (Frequent Guest)', 'Airline', ARRAY['Platinum','Gold','Silver','Teal']::text[], false, 388),
  ('loyalty_programme', 'windstar_cruises_yacht_club', 'Windstar Cruises Yacht Club', 'Cruise', ARRAY['One Star','Two Star','Three Star','Four Star']::text[], false, 389),
  ('loyalty_programme', 'wizz_air', 'Wizz Air (Discount Club)', 'Airline', ARRAY['Group membership','Standard']::text[], false, 390),
  ('loyalty_programme', 'world_of_hyatt', 'World of Hyatt', 'Hotel', ARRAY['Globalist','Explorist','Discoverist','Member']::text[], false, 178),
  ('loyalty_programme', 'wyndham_rewards', 'Wyndham Rewards', 'Hotel', ARRAY['Diamond','Platinum','Gold','Blue']::text[], false, 391),
  ('loyalty_programme', 'yelloh_village', 'Yelloh! Village (Yelloh! Plus)', 'Hotel', ARRAY['Member']::text[], false, 392),
  ('loyalty_programme', 'z_air_z_rewards', 'Z Air Z Rewards', 'Airline', '{}', false, 393)
ON CONFLICT ("kind", "slug") DO UPDATE SET
  "tiers" = excluded."tiers",
  "grouping" = excluded."grouping";
