import { type PreferenceKind, slugify } from "@/domain/preferences";

type Kind = PreferenceKind;

export { slugify };

export type CatalogueEntry = {
  kind: Kind;
  slug: string;
  label: string;
  grouping?: string;
};

function entries(
  kind: Kind,
  grouping: string | undefined,
  labels: string[],
): CatalogueEntry[] {
  return labels.map((label) => ({
    kind,
    slug: slugify(label),
    label,
    grouping,
  }));
}

/**
 * Opening vocabulary for every multi-select in the requirements document.
 *
 * This is a starting point, not a closed list. Staff can add options at runtime
 * and those are stored with isCustom = true.
 */
export const CATALOGUE: CatalogueEntry[] = [
  /* ---------------- destinations ---------------- */
  ...entries("destination", "India", [
    "Rajasthan",
    "Kerala",
    "Kashmir",
    "Ladakh",
    "Goa",
    "Andaman Islands",
    "Himachal Pradesh",
    "Uttarakhand",
    "North East India",
  ]),
  ...entries("destination", "Indian Ocean", [
    "Maldives",
    "Sri Lanka",
    "Seychelles",
    "Mauritius",
  ]),
  ...entries("destination", "Asia", [
    "Japan",
    "Thailand",
    "Vietnam",
    "Bali",
    "Singapore",
    "Bhutan",
    "Nepal",
    "South Korea",
    "Cambodia",
    "Hong Kong",
  ]),
  ...entries("destination", "Europe", [
    "Italy",
    "France",
    "Switzerland",
    "Spain",
    "Portugal",
    "Greece",
    "Croatia",
    "Austria",
    "Iceland",
    "Norway",
    "United Kingdom",
    "Ireland",
    "Germany",
    "Turkey",
  ]),
  ...entries("destination", "Africa", [
    "Kenya",
    "Tanzania",
    "South Africa",
    "Botswana",
    "Namibia",
    "Rwanda",
    "Morocco",
    "Egypt",
  ]),
  ...entries("destination", "Middle East", [
    "United Arab Emirates",
    "Oman",
    "Jordan",
    "Qatar",
    "Saudi Arabia",
  ]),
  ...entries("destination", "Americas", [
    "United States",
    "Canada",
    "Mexico",
    "Brazil",
    "Argentina",
    "Peru",
    "Chile",
    "Costa Rica",
    "Galapagos Islands",
  ]),
  ...entries("destination", "Oceania and Polar", [
    "Australia",
    "New Zealand",
    "Fiji",
    "French Polynesia",
    "Antarctica",
  ]),

  /* ---------------- travel style ---------------- */
  ...entries("travel_style", undefined, [
    "Luxury",
    "Adventure",
    "Wellness",
    "Beach",
    "Safari",
    "Culture",
    "Gastronomy",
    "Shopping",
    "Ski",
    "Family",
    "Romantic",
    "Art and Design",
    "Sports and Events",
  ]),

  /* ---------------- seasons ---------------- */
  ...entries("travel_season", undefined, [
    "Spring",
    "Summer",
    "Autumn",
    "Winter",
    "Cherry Blossom",
    "Festive and New Year",
    "Monsoon",
    "Shoulder Season",
    "School Holidays",
  ]),

  /* ---------------- hotel brands ---------------- */
  ...entries("hotel_brand", "Ultra luxury", [
    "Aman",
    "Four Seasons",
    "Belmond",
    "Rosewood",
    "Mandarin Oriental",
    "Bulgari Hotels",
    "Cheval Blanc",
    "One and Only",
    "Soneva",
    "Six Senses",
    "Capella",
    "COMO Hotels",
    "Auberge Resorts",
    "Raffles",
    "The Peninsula",
  ]),
  ...entries("hotel_brand", "Luxury", [
    "Ritz-Carlton",
    "St. Regis",
    "Park Hyatt",
    "Waldorf Astoria",
    "Anantara",
    "Banyan Tree",
    "Edition",
    "Nobu Hotels",
    "Relais and Chateaux",
    "Conrad",
    "InterContinental",
  ]),
  ...entries("hotel_brand", "India", [
    "Oberoi",
    "Taj Hotels",
    "The Leela",
    "ITC Hotels",
    "Postcard Hotels",
  ]),

  /* ---------------- room and bed ---------------- */
  ...entries("room_type", undefined, [
    "Suite",
    "Junior Suite",
    "Presidential Suite",
    "Private Villa",
    "Pool Villa",
    "Overwater Villa",
    "Club Room",
    "Deluxe Room",
    "Penthouse",
    "Connecting Rooms",
    "Adjacent Rooms",
  ]),
  ...entries("bed_preference", undefined, [
    "King Bed",
    "Super King Bed",
    "Twin Beds",
    "Firm Mattress",
    "Soft Mattress",
    "Extra Pillows",
    "Hypoallergenic Bedding",
    "Blackout Curtains",
  ]),
  ...entries("view_preference", undefined, [
    "Ocean View",
    "Beachfront",
    "Mountain View",
    "City Skyline",
    "Garden View",
    "Pool View",
    "High Floor",
    "Quiet Side",
    "Sunset Facing",
  ]),

  /* ---------------- air ---------------- */
  ...entries("airline", "Middle East", [
    "Emirates",
    "Qatar Airways",
    "Etihad Airways",
  ]),
  ...entries("airline", "Asia Pacific", [
    "Singapore Airlines",
    "Cathay Pacific",
    "Japan Airlines",
    "ANA",
    "Thai Airways",
    "Qantas",
  ]),
  ...entries("airline", "Europe", [
    "Lufthansa",
    "Swiss International",
    "British Airways",
    "Air France",
    "KLM",
    "Turkish Airlines",
    "Virgin Atlantic",
  ]),
  ...entries("airline", "India", ["Air India", "IndiGo", "Akasa Air"]),
  ...entries("airline", "Americas", [
    "Delta Air Lines",
    "United Airlines",
    "American Airlines",
  ]),

  ...entries("loyalty_programme", "Airline", [
    "Emirates Skywards",
    "Qatar Privilege Club",
    "Singapore KrisFlyer",
    "Etihad Guest",
    "Miles and More",
    "British Airways Executive Club",
    "Air France KLM Flying Blue",
    "Cathay Asia Miles",
    "Air India Maharaja Club",
  ]),
  ...entries("loyalty_programme", "Hotel", [
    "Marriott Bonvoy",
    "Hilton Honors",
    "World of Hyatt",
    "Accor ALL",
    "IHG One Rewards",
    "Taj InnerCircle",
    "Oberoi One",
  ]),

  ...entries("seat_preference", undefined, [
    "Aisle Seat",
    "Window Seat",
    "Bulkhead",
    "Exit Row",
    "Front of Cabin",
    "Rear of Cabin",
    "Seats Together",
    "Away from Galley",
    "Away from Lavatory",
  ]),
  ...entries("flight_timing", undefined, [
    "Early Morning",
    "Mid Morning",
    "Afternoon",
    "Evening",
    "Overnight Red-eye",
  ]),

  /* ---------------- dining ---------------- */
  ...entries("cuisine", undefined, [
    "Japanese",
    "Italian",
    "French",
    "Indian",
    "Thai",
    "Chinese",
    "Mediterranean",
    "Middle Eastern",
    "Spanish",
    "Korean",
    "Vietnamese",
    "Mexican",
    "Peruvian",
    "Greek",
    "Seafood",
    "Steakhouse",
    "Vegetarian Fine Dining",
    "Modern Fusion",
  ]),
  ...entries("allergy", undefined, [
    "Tree Nuts",
    "Peanuts",
    "Shellfish",
    "Fish",
    "Gluten",
    "Dairy and Lactose",
    "Eggs",
    "Soy",
    "Sesame",
    "Mushrooms",
    "Chilli and Spice",
  ]),
  ...entries("beverage_preference", undefined, [
    "Red Wine",
    "White Wine",
    "Champagne",
    "Single Malt Whisky",
    "Cocktails",
    "Sake",
    "Craft Beer",
    "Tequila and Mezcal",
    "Cognac",
    "Non Alcoholic",
  ]),

  /* ---------------- lifestyle ---------------- */
  ...entries("interest", undefined, [
    "Art",
    "Architecture",
    "History",
    "Music",
    "Wildlife",
    "Photography",
    "Wine",
    "Golf",
    "Formula 1",
    "Tennis",
    "Cricket",
    "Football",
    "Fashion",
    "Literature",
    "Spirituality",
    "Design",
    "Classic Cars",
    "Yachting",
  ]),
  ...entries("activity", undefined, [
    "Scuba Diving",
    "Snorkelling",
    "Hiking and Trekking",
    "Skiing",
    "Spa and Wellness",
    "Yoga and Meditation",
    "Golf",
    "Cycling",
    "Sailing",
    "Hot Air Ballooning",
    "Cooking Classes",
    "Private Guided Tours",
    "Gallery and Museum Visits",
    "Safari Game Drives",
    "Helicopter Tours",
    "Wine Tasting",
  ]),
  ...entries("luxury_brand", undefined, [
    "Hermes",
    "Chanel",
    "Louis Vuitton",
    "Dior",
    "Gucci",
    "Prada",
    "Bottega Veneta",
    "Loro Piana",
    "Brunello Cucinelli",
    "Rolex",
    "Patek Philippe",
    "Audemars Piguet",
    "Cartier",
    "Van Cleef and Arpels",
    "Bvlgari",
  ]),
];
